#Welcome to the Trails config.
General:
    ## Language files are located in /plugins/Trails/lang. Default is en-US.yml. If you edit one into a new language, try to rename the file with a language code from
    ## https://www.alchemysoftware.com/livedocs/ezscript/Topics/Catalyst/Language.htm such as zh.yml or zh-CHS.yml for simplified Chinese for example. You can then set 
    ## this setting here in this file to zh or zh-CHS and it will load properly. If you create a new language file, please send it to me so I can include it in future
    ## updates of the project for all to enjoy! (Email: DrkMatr1984@aol.com)
    Language: en-US
    # If set to true path creation will be enabled by default for all players
    # To turn it off execute command /trails or /trails off
    enabled-by-default: true
    # The same for speed boost on trails. /trails boost to switch
    boost-enabled-by-default: true
    # Chance to increment amount of walks = modifier * base chance
    run-modifier: 1.5
    # Do not create trails while sneaking
    sneak-bypass: true
    # Boost is applied gradually to reduce stutter. This value represents pause between each speed boost.
    # 1 means boost is applied each tick (20 times per second)
    speed-boost-interval: 1
    # Speed increment which is applied. Base speed = 0.2
    speed-boost-step: 0.006
    # Some blocks may have the same material as a trail, but it was not created as one. Should speed boost be applied only on true trail blocks?
    speed-boost-only-rrails: true
    # If this is enabled players with "trails.create-trails" permission will create trails.
    use-permission-for-trails: false
    # If this is enabled players with "trails.boost" will be boosted
    use-permission-for-boost: false
    # Immediately remove boost when stepping on non-trail block
    immediately-remove-boost: false
    # Tool to create trails. Right click to increment level. Requires "trails.trail-tool" permission. "trails.trail-tool.bypass-protection" allows to create trails anywhere
    trail-tool: iron_shovel
    # Tool to check block status. Right click a block to see. Requires "trails.info-tool" permission
    info-tool: stick
    # Worlds where trails functionality will be enabled. Put 'all' int this list to enable all worlds
    enabled-worlds:
    - 'all'
# SendDenyMessage: set to true will send players a message telling them they cannot create trails in the current area if their trails are toggled on
# and a protection plugin is blocking them.
# The interval is to prevent message spamming. If they remain in an area where they can't create trails, the messages will be spaced apart by this interval,
# in seconds.
Messages:
    SendDenyMessage: 'true'
    Interval: 10  
Plugin-Integration:
    # Towny integration now works two ways. If 'PathsInWilderness' is set to true, then players will create
    # paths in the Wilderness unless individually toggled off. If TownyPathsPerm is set to true, players with 
    # "trails.towny.town" will create paths anywhere in their hometown, and players with "trails.towny.nation"
    # will create paths anywhere in their nation. Recommend setting these in Towny config permissions for 
    # Assistant, or create your own resident type "TrailMaker" and add perms to that. If TownyPathsPerm is set to false,
    # any player in their home town or nation will create trails in their own town or nation unless they have trails
    # individually toggled off. Players will never create trails in towns that aren't their own town or in their Nation.
    Towny:
        PathsInWilderness: true
        TownyPathsPerm: false
    # Lands settings affect the Role Flag. Setting PathsInWilderness: 'true' will always allow paths in wilderness.
    # Setting ApplyInSubAreas: 'true' cause the flag to also be applied in Sub Areas, not just the individual area you have toggled
    # it on in. (Whole Towns/Lands versus individual plots)
    Lands:
        PathsInWilderness: true
        ApplyInSubAreas: true
    # GriefPrevention is automatically detected. If it is found, players must have Build permission to build in a claim. If 'PathsInWilderness' is set to true,
    # then players will create paths in the Wilderness unless individually toggled off.
    GriefPrevention:
        PathsInWilderness: true
    # WorldGuard is automatically detected. Regions with the Trails flag set to false will be protected from trails. Trails flag is trails-flag. Setting 
    # "checkBypass: 'true'" will allow OPs to use trails anywhere regardless of Region settings.
    WorldGuard:
        IntegrationEnabled: true
        CheckBypass: false
    # LogBlock and CoreProtect settings both work the same. If set to true and LogBlock and/or CoreProtect are installed, Trails will create rollback data
    # when blocks change using Trails. 
    LogBlock:
        LogPathBlocks: true
    CoreProtect:
        LogPathBlocks: true
    
  ##  Trails are composed of "Links" separated by a ">". Each link comprises 3 numbers: the material, walks to degrade to the next link,
  ## and the percent chance of it occurring. They should follow the following format "material:walks:chance". If you want it to instantly change, change
  ## walks to 0.
  ## Get material names from https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html 
  ## WARNING: If two trails have one of the same material value links, all Trails will fail. Make sure no two links are the same!
Trails:
    # This is a Link! Link name MUST NOT CONTAIN symbol ":"
    DirtPath: 'GRASS_BLOCK:5:100:1.0 > DIRT:5:100:1.1 > COARSE_DIRT:7:30:1.2 > DIRT_PATH:10:100:1.3'
    # This is translated as a GRASS_BLOCK will degrade into DIRT after no more than 5 walks. After that, into COARSE_DIRT after 7 walks, but each walk has a
    # 30% chance of counting. Finally, the COARSE_DIRT will turn into DIRT_PATH after no more than 10 walks. (The step counting system is a little strange
    # sometimes so you may have to tinker with these numbers to get your desired results. The last number represents speed boost. Dirt path gives 130% of base speed.
    SandPath: 'SAND:0:100:1.0 > SANDSTONE:5:30:1.3'
    # Data-Saving allows you to set, in minutes, how often you would like Trails to save it's internal data to disk. It saves async! :)
    # Link may contain the same material entries
    # But DO NOT have 2 links which start with THE SAME block material. Because it is dumb.
    # DirtPath2: 'GRASS_BLOCK:5:100:1.0 > GRASS_BLOCK:5:100:1.0 > GRASS_BLOCK:5:100:1.0'
Data-Saving:
    Interval: 5   