#Welcome to the Trails config. If you would like to add Towny support (no trails in cities), change HookTowny to true.
#WorldGuard is automatically detected and players that cannot build in specific regions will not generate trails
HookTowny: false
#Trails are composed of "Links" separated by a ">". Each link is comprised of 3 numbers: the material/datavalue(done like WOOL;4), walks to degrade to the next link, 
# and the percent chance of it occuring. They should follow the followin format "material/datavalue:walks:chance". If you want it to instantly change, change
# walks to 0. 

#WARNING: If two trails have one of the same material value links (the first number), all Trails will fail. Make sure no two links are the same!
Trails:
    DirtPath: 'GRASS:5:100>DIRT:5:100>DIRT;1:5:100>GRAVEL:7:30>SMOOTH_BRICK;2:10:100'
    SandPath: 'SAND:0:100>SANDSTONE:5:30'