#Welcome to the Trails config.
#WorldGuard is automatically detected. Regions with the Trails flag set to false will be protected from trails. Trails flag is trails-flag
#Trails are composed of "Links" separated by a ">". Each link comprises 3 numbers: the material, walks to degrade to the next link,
# and the percent chance of it occurring. They should follow the following format "material:walks:chance". If you want it to instantly change, change
# walks to 0.
# Get material names from https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html 

#WARNING: If two trails have one of the same material value links, all Trails will fail. Make sure no two links are the same!
Trails:
    DirtPath: 'GRASS_BLOCK:5:100>DIRT:5:100>GRAVEL:7:30>SMOOTH_STONE:10:100'
    SandPath: 'SAND:0:100>SANDSTONE:5:30'
Plugin-Integration:
    # Towny integration now works two ways. If 'PathsInWilderness' is set to true, then players will create
    #  paths in the Wilderness unless individually toggled off. If TownyPathsPerm is set to true, players with 
    #  "trails.towny.town" will create paths anywhere in their hometown, and players with "trails.towny.nation"
    #  will create paths anywhere in their nation. Recommend setting these in Towny config permissions for 
    #  Assistant, or create your own resident type "TrailMaker" and add perms to that. If TownyPathsPerm is set to false,
    #  any player in their home town or nation will create trails in their own town or nation unless they have trails
    #  individually toggled off.
    Towny:
        PathsInWilderness: 'true'
        TownyPathsPerm: 'true'
    LogBlock:
        LogPathBlocks: 'true'
Saves:
    Interval: 20
    SaveOnShutdown: false