name: Trails
main: me.ccrama.Trails.Trails
authors: [j10max, ccrama, drkmatr1984, Mr-Deej]
api-version: 1.17
softdepend: [WorldGuard, WorldEdit, Towny, Lands, LogBlock, CoreProtect, PlaceholderAPI, MVdWPlaceholderAPI, GriefPrevention]
version: 1.0
description: Naturally create paths whereever you go!

permissions:
    trails.toggle:
        description: Toggles a player's trails on/off
        default: true
    trails.other:
        description: Toggles a different player's trails on/off
        default: false
    trails.towny.town:
        description: Can assign to Town roles to allow them to make trails (Enable TownyPathsPerms in config)
        default: false
    trails.towny.nation:
        description: Can assign to Nation roles to allow them to make trails (Enable TownyPathsPerms in config)
        default: false