name: Trails
main: me.ccrama.Trails.Trails
authors: [j10max, ccrama, drkmatr1984, Mr-Deej, GrocerMC]
api-version: 1.16
softdepend: [PlayerPlot, RedProtect, WorldGuard, WorldEdit, Towny, Lands, LogBlock, CoreProtect, PlaceholderAPI, MVdWPlaceholderAPI, GriefPrevention, Dynmap, dynmap, Residence]
version: 1.9
description: Naturally create paths whereever you go!

permissions:
    trails.toggle:
        description: Toggles a player's trails on/off
        default: true