name: Trails
main: me.ccrama.Trails.Trails
authors: [j10max, ccrama, drkmatr1984, Mr-Deej]
api-version: 1.17
softdepend: [WorldGuard, WorldEdit, Towny, Lands, LogBlock, CoreProtect, PlaceholderAPI, MVdWPlaceholderAPI, GriefPrevention, Dynmap, dynmap]
version: 1.0
description: Naturally create paths whereever you go!

permissions:
    trails.toggle:
        description: Toggles a player's trails on/off
        default: true